# Generated by Django 2.1.7 on 2019-04-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20190427_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
