# Generated by Django 2.1.7 on 2019-04-29 10:07

from django.db import migrations, models
import newsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_auto_20190429_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='file',
            field=models.FileField(default=1, upload_to=newsapp.models.get_image_filename, verbose_name='File'),
            preserve_default=False,
        ),
    ]
