# Generated by Django 2.1.7 on 2019-04-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_images_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='file',
        ),
    ]
